build-job:
  stage: build
  script:
    - echo "Building..."
    - cp /home/defi/backend/application.properties ./src/main/resources
    - chmod +x mvnw
    - ./mvnw clean install

test-job:
  stage: test
  script:
    - echo "Testing..."
    - cp /home/defi/backend/application.properties ./src/main/resources
    - chmod +x mvnw
    - ./mvnw clean test

deploy-dev:
  stage: deploy
  script:
    - echo "Deploying..."
    - cp /home/defi/backend/application.properties ./src/main/resources
    - chmod +x mvnw
    - ./mvnw clean install
    - echo "Deploying to dev system"
    - sudo systemctl stop defi-backend
    - cp ./target/kreuzen.jar /home/defi/backend/kreuzen.jar
    - sudo systemctl start defi-backend
  only:
    - master
    - develop
    - feature/auth
